inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Lint/NonLocalExitFromIterator:
  Exclude:
    - 'lib/mask_sql/converter.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Style/IndentHeredoc:
  Exclude:
    - 'spec/mask_sql/cli_spec.rb'

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingWhitespace:
  Enabled: false
