inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Lint/NonLocalExitFromIterator:
  Exclude:
    - 'lib/mask_sql/converter.rb'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/IndentHeredoc:
  Exclude:
    - 'spec/mask_sql/cli_spec.rb'

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingWhitespace:
  Enabled: false
