sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
before_install:
  - gem update --system || gem install rubygems-update -v '<3' && update_rubygems
  - gem update bundler || gem install bundler -v '<2'
