mark: '[mask]'
targets:
  - table: people
    columns: 4
    indexes:
      2: 氏名[mask]
      3: email-[mask]@example.com
  - table: cats
    columns: 2
    indexes:
      0: code-[mask]
      1: Cat name [mask]
